[package]
name = "tepsim-wasm"
description = "WebAssembly bindings for the Tennessee Eastman Process simulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true
