//! Python bindings for the Tennessee Eastman Process simulator.
//!
//! The extension module is `tepsim._tepsim`. What a user imports is `tepsim`,
//! the small pure-Python package in `python/tepsim` that re-exports this one
//! and carries the type stubs a compiled module cannot.
//!
//! # Shape of the binding
//!
//! Three objects and a table, mirroring [`tepsim`]'s facade rather than
//! inventing a second vocabulary: a [`Scenario`] says what to simulate, a
//! [`Simulation`] runs it, a [`Run`] is what came out, and [`faults`] is the
//! twenty disturbances with what each one actually does.
//!
//! ```python
//! import tepsim as tep
//!
//! run = tep.Simulation(tep.Scenario.baseline(seed=42, hours=48)).run()
//! matrix = run.to_numpy()          # (n_samples, 53) float64
//! ```
//!
//! # Why `unsafe` appears in this crate at all
//!
//! `tepsim-core` is `#![forbid(unsafe_code)]` and the rest of the workspace
//! follows it. This crate cannot: a CPython extension module is an FFI
//! boundary, and `#[pyclass]`, `#[pyfunction]` and `#[pymodule]` expand to
//! `unsafe extern "C"` entry points. Every one of those is generated by pyo3
//! rather than written here, and `unsafe_op_in_unsafe_fn` is denied so that a
//! hand-written one would have to say so explicitly.
//!
//! There is no hand-written `unsafe` block in this crate. The one operation
//! that would normally need one, marking a NumPy array read-only, is reached
//! through `numpy`'s safe `make_nonwriteable`. See [`run`].
//!
//! # Copies
//!
//! Exactly one, per array, when a [`Run`] is constructed: the samples arrive as
//! a `Vec` of structs interleaving measurements with step numbers and labels,
//! and NumPy needs a contiguous block per array. That block is built once and
//! moved into NumPy without a second copy. Every accessor afterwards
//! (`Run.to_numpy`, `Run.measurement`, `Run.columns`) is a view over
//! it and copies nothing.

#![deny(unsafe_op_in_unsafe_fn)]

use pyo3::prelude::*;
use pyo3::types::PyTuple;

pub mod fault;
pub mod run;
pub mod scenario;
pub mod sim;

pub use fault::{Fault, faults};
pub use run::Run;
pub use scenario::Scenario;
pub use sim::Simulation;

/// Short, stable names for the 53 recorded channels, in row order.
///
/// The keys of [`Run::columns`] and the header a CSV of [`Run::to_numpy`]
/// wants. Measurement names follow Downs and Vogel's Table 4 and the
/// manipulated ones their Table 3.
#[pyfunction]
fn channel_names(py: Python<'_>) -> PyResult<Bound<'_, PyTuple>> {
    PyTuple::new(py, tepsim::channel_names())
}

/// `tepsim._tepsim`: the compiled half of the `tepsim` package.
#[pymodule]
fn _tepsim(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<Scenario>()?;
    m.add_class::<Simulation>()?;
    m.add_class::<Run>()?;
    m.add_class::<Fault>()?;
    m.add_function(wrap_pyfunction!(faults, m)?)?;
    m.add_function(wrap_pyfunction!(channel_names, m)?)?;

    m.add("__version__", env!("CARGO_PKG_VERSION"))?;

    // The dimensions a caller needs to allocate against, named rather than
    // spelled 41 and 12 at every call site.
    m.add("MEASUREMENTS", tepsim::MEASUREMENTS)?;
    m.add("MANIPULATED", tepsim::MANIPULATED)?;
    m.add("CHANNELS", tepsim::CHANNELS)?;
    m.add("DISTURBANCES", tepsim::DISTURBANCES)?;

    // The defaults, exposed so a caller can see what `Scenario()` means
    // without reading the source.
    m.add("DEFAULT_SEED", tepsim::scenario::DEFAULT_SEED)?;
    m.add("DEFAULT_STEP_HOURS", tepsim::scenario::DEFAULT_STEP_HOURS)?;
    m.add(
        "DEFAULT_SAMPLE_EVERY",
        tepsim::scenario::DEFAULT_SAMPLE_EVERY,
    )?;

    // `temain_mod.f:366-368` forces IDV(12) on at this step whatever the
    // scenario asked for. Delta D-011, and a caller labelling data needs it.
    m.add("FORCED_DISTURBANCE_STEP", tepsim::forced_disturbance_step())?;

    Ok(())
}
